// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vdqycwjbjhdgsmrlwyop.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZkcXljd2piamhkZ3Ntcmx3eW9wIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDc4MjUwMzAsImV4cCI6MjA2MzQwMTAzMH0.gnN2sdJ1NNMuaDhCPXaoy4MEtgRE_uB9qqlQw5nUHjc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);